version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    cmds:
      - pnpm install
      - pnpm prune
    sources:
      - package.json
    generates:
      - pnpm-lock.yaml

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build
    sources:
      - .eslintrc.js
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - vite.config.ts
      - src/*
    generates:
      - dist/*

  story-dev:
    desc: Story - Dev
    deps: [ install ]
    cmds:
      - pnpm run story:dev

  story-build:
    desc: Story - Build
    deps: [ install ]
    cmds:
      - rm -rf build/histoire
      - pnpm run story:build
    sources:
      - .eslintrc.js
      - histoire.config.ts
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
      - vite.config.ts
      - src/*
      - src/stories/*
    generates:
      - build/histoire/*

  typedoc:
    desc: Generate typedoc
    deps: [ install ]
    cmds:
      - rm -rf build/typedoc
      - pnpm run typedoc
    sources:
      - package.json
      - pnpm-lock.yaml
      - README.md
      - screenshot.png
      - tsconfig.json
      - typedoc.json
      - src/*
    generates:
      - build/typedoc/*

  site-build:
    desc: Site - Build
    deps: [ story-build, typedoc ]
    cmds:
      - rm -rf build/site
      - mkdir -p build/site
      - cp -r build/histoire/* build/site/
      - cp -r build/typedoc build/site/
      - cp -r examples build/site/
    generates:
      - build/site/*

  site-serve:
    desc: Site - Serve
    deps: [ site-build ]
    cmds:
      - pnpm dlx sirv-cli build/site
