version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    cmds:
      - pnpm install
      - pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build

  npm-publish:
    desc: NPM - Publish
    deps: [ build ]
    cmds:
      - pnpm publish --access public

  site-clean:
    desc: Site - Clean
    cmds:
      - rm -rf build/gh-pages

  site-build:
    desc: Site - Build
    cmds:
      - task: site-clean
      - mkdir -p build/gh-pages
      - task: site-build-mdbook
      - task: site-build-typedoc
      - task: site-build-example-basic

  site-build-mdbook:
    desc: Site - mdbook
    cmds:
      - mdbook build --dest-dir $(pwd)/build/gh-pages docs/mdbook

  site-build-typedoc:
    desc: Site - typedoc
    deps: [ install ]
    cmds:
      - pnpm run typedoc

  site-build-example-basic:
    cmds:
      - cd examples/basic && mise exec -- task build
      - cp -r examples/basic/dist build/gh-pages/projects/basic

  site-serve:
    desc: Site - Serve
    deps: [ site-build ]
    cmds:
      - caddy file-server --root build/gh-pages --listen 127.0.0.1:8080

  site-publish:
    desc: Site - Publish
    deps: [ site-build ]
    cmds:
      - gh-pages --dotfiles --dist build/gh-pages
