version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    cmds:
      - pnpm install
      - pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm build

  typedoc:
    desc: Generate typedoc
    deps: [ install ]
    cmds:
      - rm -rf build/typedoc
      - pnpm run typedoc

  site-build:
    desc: Site - Build
    deps: [ story-build, typedoc ]
    cmds:
      - rm -rf build/site
      - mkdir -p build/site/leaflet-tracksymbol2
      - cp -r build/histoire/* build/site/leaflet-tracksymbol2/
      - cp -r build/typedoc build/site/leaflet-tracksymbol2/
      - cp -r examples build/site/leaflet-tracksymbol2/
      - touch build/site/leaflet-tracksymbol2/.nojekyll
    generates:
      - build/site/*

  site-serve:
    desc: Site - Serve
    deps: [ site-build ]
    cmds:
      - caddy file-server --root build/site --listen 127.0.0.1:8080

  site-publish:
    desc: Site - Publish
    deps: [ site-build ]
    cmds:
      - gh-pages --dotfiles --dist build/site/leaflet-tracksymbol2

  npm-publish:
    desc: NPM - Publish
    deps: [ build ]
    cmds:
      - pnpm publish --access public
