version: 3

tasks:
  clean:
    desc: Clean
    cmds:
      - rm -rf build dist

  install:
    desc: Install dependencies
    cmds:
      - pnpm install
      - pnpm prune

  install-lib:
    desc: Install local lib
    deps: [ build-lib ]
    cmds:
      - eval `mise env` && task build
      - pnpm uninstall @arl/leaflet-tracksymbol2
      - pnpm install ../leaflet-tracksymbol2

  check:
    desc: Check
    deps: [ install ]
    cmds:
      - pnpm build

  dev:
    desc: Dev
    deps: [ install ]
    cmds:
      - pnpm run story:dev

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run story:build
      - rm -rf build/site
      - mkdir -p build/site
      - cp -r build/histoire build/site/leaflet-tracksymbol2
      - cp -r examples build/site/leaflet-tracksymbol2

  preview:
    desc: Preview
    deps: [ build ]
    cmds:
      - caddy file-server --root build/site --listen 127.0.0.1:8080
